"""
Last week some of South Korea's biggest banks were hit by a cyberattack. We now know the entire hack may have been done by a single person. He used a combined stack of an open-source AI penetration tool named ARTEX, DeepSeek v4.1-Flash, GLM-5.3, Grok 4.6, and Claude Code (CrowdStrike)
Starter automation script generated by Musfira AI.
Replace the placeholder logic below with your implementation.
"""

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"


def query_local_llm(prompt: str, model: str = "llama3") -> str:
    resp = requests.post(
        OLLAMA_URL,
        json={"model": model, "prompt": prompt, "stream": False},
        timeout=60,
    )
    resp.raise_for_status()
    return resp.json().get("response", "")


def main() -> None:
    prompt = "Summarize the latest update on: Last week some of South Korea's biggest banks were hit by a cyberattack. We now know the entire hack may have been done by a single person. He used a combined stack of an open-source AI penetration tool named ARTEX, DeepSeek v4.1-Flash, GLM-5.3, Grok 4.6, and Claude Code (CrowdStrike)"
    print(query_local_llm(prompt))


if __name__ == "__main__":
    main()
